# -*- coding: utf-8 -*-
"""rsitmd_svm_feature_pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOFHSm4NuCqdzL_Z0ee-nHvojqHQyx4p
"""

# ==========================================
# PYTORCH EXTRACTOR + SVM (AUGMENTATION CLONE)
# ==========================================
# Augmentation clone: train-time transforms are stronger than the non-augmentation baseline.
import os
import random
import time
from collections import Counter

import torch
import torch.nn as nn
from torchvision import models, transforms
from torch.utils.data import DataLoader, Dataset
from datasets import load_from_disk
import kagglehub
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, balanced_accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.model_selection import learning_curve
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import joblib
import json

# 1. SETUP & DATA LOADING
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

print("Downloading dataset...")
path = kagglehub.dataset_download("phantrntngvyk64cntt/processed-rsitmd-256-clean")
hf_dataset = load_from_disk(path)
output_dir = "outputs_svm_au"
os.makedirs(output_dir, exist_ok=True)

try:
    class_names = hf_dataset['train'].features['label'].names
except AttributeError:
    unique_labels = set(hf_dataset['train']['label'])
    class_names = [str(label) for label in sorted(unique_labels)]

# 2. PREPROCESSING
# NOTE: Augmentation clone — stronger train-time image pipeline for the ResNet50 extractor.
train_preprocess = transforms.Compose([
    transforms.RandomResizedCrop((224, 224), scale=(0.65, 0.7)),
    transforms.RandomRotation(10),
    transforms.RandomPerspective(distortion_scale=0.15, p=0.5),
    transforms.RandomAffine(degrees=0, translate=(0.05, 0.05), scale=(0.95, 1.05), shear=5),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.18, contrast=0.18, saturation=0.12, hue=0.04),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def transform_split(example, split_name):
    image = example["image"].convert("RGB")
    if split_name == "train":
        example["pixel_values"] = train_preprocess(image)
    else:
        example["pixel_values"] = eval_preprocess(image)
    return example

print("Applying transformations dynamically...")

hf_dataset = hf_dataset.map(lambda ex, idx: transform_split(ex, "train"), with_indices=True, load_from_cache_file=False) if False else hf_dataset

# Use split-specific transforms so train augmentation stays stronger while val/test remain stable.
class AugmentedHFImageDataset(Dataset):
    def __init__(self, hf_split, transform=None):
        self.ds = hf_split
        self.transform = transform
    def __len__(self):
        return len(self.ds)
    def __getitem__(self, idx):
        ex = self.ds[idx]
        img = ex["image"].convert("RGB")
        label = ex["label"]
        pixel_values = self.transform(img) if self.transform is not None else img
        return {"pixel_values": pixel_values, "label": label}

train_loader = DataLoader(AugmentedHFImageDataset(hf_dataset["train"], train_preprocess), batch_size=32, shuffle=True)
val_loader = DataLoader(AugmentedHFImageDataset(hf_dataset["validation"], eval_preprocess), batch_size=32, shuffle=False)
test_loader = DataLoader(AugmentedHFImageDataset(hf_dataset["test"], eval_preprocess), batch_size=32, shuffle=False)

# 3. BUILD EXTRACTOR
print("Building ResNet50 Extractor...")
extractor = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
extractor.fc = nn.Identity() # Remove the final layer!
extractor = extractor.to(device)
extractor.eval()

# 4. EXTRACT FEATURES
def extract_features(dataloader, model_extractor):
    features_list, labels_list = [], []
    with torch.no_grad():
        for batch in dataloader:
            inputs = batch["pixel_values"].to(device)
            labels = batch["label"].numpy()
            features = model_extractor(inputs).cpu().numpy()
            features_list.append(features)
            labels_list.extend(labels)
    return np.vstack(features_list), np.array(labels_list)

print("Extracting features (this might take a minute)...")
X_train, y_train = extract_features(train_loader, extractor)
X_val, y_val = extract_features(val_loader, extractor)
X_test, y_test = extract_features(test_loader, extractor)

# 5. TRAIN SVM
print("Training SVM...")
svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train, y_train)

# 6. EVALUATION & CONFUSION MATRIX
print("\nEvaluating...")
start_eval = time.time()
y_pred = svm.predict(X_val)
eval_sec = time.time() - start_eval
svm_acc = accuracy_score(y_val, y_pred)
svm_bal_acc = balanced_accuracy_score(y_val, y_pred)
svm_macro_f1 = f1_score(y_val, y_pred, average='macro', zero_division=0)
ms_per_batch = 1000.0 * eval_sec
images_per_sec = (len(X_val) / eval_sec) if eval_sec > 0 else None
print(f"SVM Accuracy: {svm_acc:.4f}")
print(f"SVM Balanced Accuracy: {svm_bal_acc:.4f}")
print(f"SVM Macro F1: {svm_macro_f1:.4f}")
print(f"Inference Time: {ms_per_batch:.4f} ms/batch | {images_per_sec:.4f} images/sec")
gpu_peak_mb = (torch.cuda.max_memory_allocated(device) / (1024 ** 2)) if device.type == "cuda" else None
print(f"GPU Peak Memory: {gpu_peak_mb:.4f} MB" if gpu_peak_mb is not None else "GPU Peak Memory: N/A (CPU)")
print("Classification Report:\n", classification_report(y_val, y_pred, target_names=class_names, zero_division=0, digits=4))

print("Evaluating on test set for final confusion matrix...")
y_test_pred = svm.predict(X_test)
label_ids = list(range(len(class_names)))
print("Test Classification Report:\n", classification_report(y_test, y_test_pred, labels=label_ids, target_names=class_names, zero_division=0, digits=4))
cm = confusion_matrix(y_test, y_test_pred, labels=label_ids)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', xticklabels=class_names, yticklabels=class_names)
plt.title('SVM Test Confusion Matrix')
plt.xlabel('SVM Predicted'); plt.ylabel('Actual')
plt.xticks(rotation=45, ha='right'); plt.tight_layout()
cm_path = os.path.join(output_dir, 'confusion_matrix.png')
plt.savefig(cm_path, dpi=200, bbox_inches='tight')
plt.show()



# 7. SAVE MODELS & METADATA
print("\nSaving deployable files...")
joblib.dump(svm, 'svm_model.joblib')
torch.save(extractor.state_dict(), "resnet50_extractor.pt")

with open("label_mapping.json", "w") as f:
    json.dump({"id2label": {int(i): name for i, name in enumerate(class_names)}}, f, indent=4)

report = {
    "model": "SVM + ResNet50 Features (augmentation)",
    "metrics": {
        "accuracy": float(svm_acc),
        "balanced_accuracy": float(svm_bal_acc),
        "macro_f1": float(svm_macro_f1),
    },
    "timing": {
        "inference": {
            "ms_per_batch": float(ms_per_batch),
            "images_per_sec": float(images_per_sec) if images_per_sec is not None else None,
        },
        "training_time_sec": None,
    },
    "gpu_peak_mb": float(gpu_peak_mb) if gpu_peak_mb is not None else None,
    "artifacts": {
        "confusion_matrix": cm_path,
        "learning_curves": learning_curve_path,
    },
}
with open(os.path.join(output_dir, "svm_report.json"), "w") as f:
    json.dump(report, f, indent=2)
print("✅ Saved: svm_model.joblib, resnet50_extractor.pt, label_mapping.json, svm_report.json")

# Feature visualization removed: the previous figure was a pseudo attention map
# derived from intermediate ResNet activations, not a true attention mechanism.
# The script now stops after saving the deployable artifacts and metrics.
