# -*- coding: utf-8 -*-
"""rsitmd_svm_feature_pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PhHGIBPoVZ2HQBvV6bs_1Ur-fwSyz1B2
"""

# ==========================================
# PYTORCH EXTRACTOR + SVM
# ==========================================
import torch
import torch.nn as nn
from torchvision import models, transforms
from torch.utils.data import DataLoader
from datasets import load_from_disk
import kagglehub
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import joblib
import json

import os
import datasets

# Redirect all Hugging Face temporary/cache files to Kaggle's writable folder
os.environ['HF_DATASETS_CACHE'] = '/kaggle/working/hf_cache'
datasets.config.HF_DATASETS_CACHE = '/kaggle/working/hf_cache'

# 1. SETUP & DATA LOADING
device = torch.device("cuda" if torch.cuda.is_available() else "gpu")
print(f"Using device: {device}")

print("Downloading dataset...")
path = kagglehub.dataset_download("phantrntngvyk64cntt/processed-rsitmd-256-clean")
hf_dataset = load_from_disk(path)

try:
    class_names = hf_dataset['train'].features['label'].names
except AttributeError:
    unique_labels = set(hf_dataset['train']['label'])
    class_names = [str(label) for label in sorted(unique_labels)]

preprocess = transforms.Compose([
    transforms.RandomResizedCrop((224, 224), scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.RandomPerspective(distortion_scale=0.15, p=0.25),
    transforms.ColorJitter(brightness=0.18, contrast=0.18, saturation=0.12, hue=0.04),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def transform_dataset(examples):
    examples["pixel_values"] = [preprocess(img.convert("RGB")) for img in examples["image"]]
    return examples

print("Applying transformations...")

# Ensure writable temporary directories exist
writable_tmp_dir = '/kaggle/working/tmp'
cache_dir = '/kaggle/working/hf_cache'
os.makedirs(writable_tmp_dir, exist_ok=True)
os.makedirs(cache_dir, exist_ok=True)
os.environ['TMPDIR'] = writable_tmp_dir

# 1. Dynamically create a cache path for EVERY split inside the dataset
cache_files = {
    split_name: f"{cache_dir}/rsitmd_{split_name}_cache.arrow"
    for split_name in hf_dataset.keys()
}

print(f"Saving caches to: {cache_files}")

# 2. Pass the dynamically generated dictionary
hf_dataset = hf_dataset.map(
    transform_dataset,
    batched=True,
    load_from_cache_file=False,
    cache_file_names=cache_files
)

hf_dataset.set_format(type="torch", columns=["pixel_values", "label"])

# 3. Create your DataLoaders (and grab the test one too!)
train_loader = DataLoader(hf_dataset["train"], batch_size=32, shuffle=False)
val_loader = DataLoader(hf_dataset["validation"], batch_size=32, shuffle=False)

if "test" in hf_dataset:
    test_loader = DataLoader(hf_dataset["test"], batch_size=32, shuffle=False)
    print("✅ Created DataLoaders for train, validation, AND test!")
else:
    print("✅ Created DataLoaders for train and validation!")

# 3. BUILD EXTRACTOR
print("Building ResNet50 Extractor...")
extractor = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
extractor.fc = nn.Identity() # Remove the final layer!
extractor = extractor.to(device)
extractor.eval()

# 4. EXTRACT FEATURES
def extract_features(dataloader, model_extractor):
    features_list, labels_list = [], []
    with torch.no_grad():
        for batch in dataloader:
            inputs = batch["pixel_values"].to(device)
            labels = batch["label"].numpy()
            features = model_extractor(inputs).cpu().numpy()
            features_list.append(features)
            labels_list.extend(labels)
    return np.vstack(features_list), np.array(labels_list)

print("Extracting features (this might take a minute)...")
X_train, y_train = extract_features(train_loader, extractor)
X_val, y_val = extract_features(val_loader, extractor)

# 5. TRAIN SVM
print("Training SVM...")
svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train, y_train)

# 6. EVALUATION & CONFUSION MATRIX
print("\nEvaluating...")
y_pred = svm.predict(X_val)
print("SVM Accuracy:", accuracy_score(y_val, y_pred))
print("Classification Report:\n", classification_report(y_val, y_pred, target_names=class_names))

cm = confusion_matrix(y_val, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', xticklabels=class_names, yticklabels=class_names)
plt.title('SVM Validation Confusion Matrix')
plt.xlabel('SVM Predicted'); plt.ylabel('Actual')
plt.xticks(rotation=45, ha='right'); plt.tight_layout(); plt.show()

# 7. SAVE MODELS & METADATA
print("\nSaving deployable files...")
joblib.dump(svm, 'svm_model.joblib')
torch.save(extractor.state_dict(), "resnet50_extractor.pt")

with open("label_mapping.json", "w") as f:
    json.dump({"id2label": {int(i): name for i, name in enumerate(class_names)}}, f, indent=4)
print("✅ Saved: svm_model.joblib, resnet50_extractor.pt, label_mapping.json")

import torch.nn.functional as F
import hashlib

# ==========================================
# 8. TEST ON SINGLE IMAGE + DEBUG EXPORT
# ==========================================
# Change this to "test[0]", "test[5]", "validation[0]", etc.
DEBUG_SAMPLE_SPEC = os.environ.get("RSITMD_DEBUG_SAMPLE", "test[0]")
DEBUG_OUTPUT_DIR = os.environ.get("RSITMD_DEBUG_OUTPUT_DIR", "/kaggle/working/rsitmd_svm_debug")
os.makedirs(DEBUG_OUTPUT_DIR, exist_ok=True)


def parse_split_index(spec: str):
    spec = spec.strip().lower()
    if "[" not in spec or "]" not in spec:
        raise ValueError(f"Bad sample spec: {spec}. Use format like test[0] or validation[5].")
    split_name = spec.split("[")[0].strip()
    idx = int(spec[spec.find("[") + 1:spec.find("]")].strip())
    return split_name, idx


split_name, sample_idx = parse_split_index(DEBUG_SAMPLE_SPEC)
if split_name not in hf_dataset:
    raise KeyError(f"Split '{split_name}' not found. Available splits: {list(hf_dataset.keys())}")
if sample_idx < 0 or sample_idx >= len(hf_dataset[split_name]):
    raise IndexError(f"Index {sample_idx} out of range for split '{split_name}' (0..{len(hf_dataset[split_name]) - 1})")

sample = hf_dataset[split_name][sample_idx]
img_tensor = sample['pixel_values'].unsqueeze(0).to(device)
true_label_text = class_names[sample['label'].item()]

print("\n================ DEBUG SAMPLE ================")
print(f"Debug sample spec: {DEBUG_SAMPLE_SPEC}")
print(f"Resolved sample: split='{split_name}', index={sample_idx}")
print(f"True label: {true_label_text}")
print("============================================\n")

# 1. Setup a Hook to eavesdrop on ResNet50's final layer
activations = []
def forward_hook(module, input, output):
    activations.append(output)

# Attach hook to the final convolutional block
target_layer = extractor.layer4[-1]
f_hook = target_layer.register_forward_hook(forward_hook)

# 2. Extract feature and predict with SVM
with torch.no_grad(): # No gradients needed!
    single_feature = extractor(img_tensor).cpu().numpy()

pred_idx = svm.predict(single_feature)[0]
pred_prob = np.max(svm.predict_proba(single_feature)) * 100
pred_class = class_names[pred_idx]

feature_flat = single_feature.reshape(-1)
feature_debug = {
    "debug_sample_spec": DEBUG_SAMPLE_SPEC,
    "split": split_name,
    "index": sample_idx,
    "true_label": true_label_text,
    "feature_shape": list(single_feature.shape),
    "feature_mean": float(feature_flat.mean()),
    "feature_std": float(feature_flat.std()),
    "feature_min": float(feature_flat.min()),
    "feature_max": float(feature_flat.max()),
    "feature_sha256": hashlib.sha256(feature_flat.tobytes()).hexdigest(),
    "feature_head": [float(x) for x in feature_flat[:8]],
    "pred_idx": int(pred_idx),
    "pred_class": pred_class,
    "pred_prob_percent": float(pred_prob),
    "svm_classes": svm.classes_.tolist() if hasattr(svm, "classes_") else None,
    "id2label": {int(i): name for i, name in enumerate(class_names)},
}

json_path = os.path.join(DEBUG_OUTPUT_DIR, f"debug_{split_name}_{sample_idx}.json")
with open(json_path, "w", encoding="utf-8") as f:
    json.dump(feature_debug, f, indent=2, ensure_ascii=False)

text_path = os.path.join(DEBUG_OUTPUT_DIR, f"debug_{split_name}_{sample_idx}.txt")
with open(text_path, "w", encoding="utf-8") as f:
    for k, v in feature_debug.items():
        f.write(f"{k}: {v}\n")

print(f"Saved debug JSON: {json_path}")
print(f"Saved debug TXT : {text_path}")
print("Feature fingerprint:")
print(f"  shape: {feature_debug['feature_shape']}")
print(f"  mean : {feature_debug['feature_mean']:.6f}")
print(f"  std  : {feature_debug['feature_std']:.6f}")
print(f"  min/max: {feature_debug['feature_min']:.6f} / {feature_debug['feature_max']:.6f}")
print(f"  sha256: {feature_debug['feature_sha256']}")
print(f"  head  : {feature_debug['feature_head']}")
print(f"SVM classes_: {feature_debug['svm_classes']}")
print(f"id2label keys: {list(feature_debug['id2label'].keys())}")
print(f"Pred idx: {pred_idx}, pred prob: {pred_prob:.4f}%")

# 3. Process the generalized Feature Attention Map
# Take the mean of the feature maps across all channels to see general attention
captured_acts = activations[0]
heatmap = torch.mean(captured_acts, dim=1, keepdim=True)
heatmap = F.relu(heatmap) # Keep only positive attention

# Resize heatmap to match the 224x224 image
heatmap = F.interpolate(heatmap, size=(224, 224), mode='bilinear', align_corners=False)
heatmap = heatmap.squeeze().cpu().numpy()
heatmap = (heatmap - heatmap.min()) / (heatmap.max() - heatmap.min()) # Normalize

f_hook.remove() # Clean up the hook

# 4. Un-normalize the tensor to restore the true colors of the original image
mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
unnormalized_tensor = sample['pixel_values'].cpu() * std + mean
unnormalized_tensor = torch.clamp(unnormalized_tensor, 0, 1)
raw_image = transforms.ToPILImage()(unnormalized_tensor)

# ==========================================
# VISUALIZE BOTH IMAGES
# ==========================================
plt.figure(figsize=(12, 5))

# Plot 1: True Original Image
plt.subplot(1, 2, 1)
plt.imshow(raw_image)
plt.title(f"SVM Predicted: {pred_class} ({pred_prob:.2f}%)\nActual: {true_label_text}",
          color='green' if pred_class == true_label_text else 'red', fontsize=14)
plt.axis('off')

# Plot 2: Extractor Attention Map
plt.subplot(1, 2, 2)
plt.imshow(raw_image)
plt.imshow(heatmap, cmap='jet', alpha=0.5) # Overlay the heatmap
plt.title("ResNet50 Attention Map\n(What the Extractor focuses on)", fontsize=14)
plt.axis('off')

plt.tight_layout()
plt.show()
plt.show()