# -*- coding: utf-8 -*-
"""rsmitsd_cnn_pytorch_final (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SNp6mRZX8VFbYGl9y3yz7RaAXsO1B36V
"""

# ==========================================
# FULL SCRIPT: PYTORCH END-TO-END DEEP LEARNING
# ==========================================
import os
import random
import time
from collections import Counter

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from torch.utils.data import DataLoader, Dataset
from datasets import load_from_disk
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
import numpy as np
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score

# 1. SETUP & DATA LOADING
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

print("Downloading dataset...")
path = kagglehub.dataset_download("phantrntngvyk64cntt/processed-rsitmd-256-clean")

print("Path to dataset files:", path)
hf_dataset = load_from_disk(path)

# Extract class names safely
try:
    class_names = hf_dataset['train'].features['label'].names
except AttributeError:
    unique_labels = set(hf_dataset['train']['label'])
    class_names = [str(label) for label in sorted(unique_labels)]
num_classes = len(class_names)

# 2. PREPROCESSING
# NOTE: Augmentation clone — stronger train-time image pipeline so the end-to-end CNN can be compared fairly.
train_preprocess = transforms.Compose([
    transforms.RandomResizedCrop((224, 224), scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.RandomPerspective(distortion_scale=0.15, p=0.25),
    transforms.ColorJitter(brightness=0.18, contrast=0.18, saturation=0.12, hue=0.04),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

class AugmentedHFImageDataset(Dataset):
    def __init__(self, hf_split, transform=None):
        self.ds = hf_split
        self.transform = transform

    def __len__(self):
        return len(self.ds)

    def __getitem__(self, idx):
        ex = self.ds[idx]
        img = ex["image"].convert("RGB")
        label = ex["label"]
        if self.transform is not None:
            img = self.transform(img)
        return {"pixel_values": img, "label": label}

print("Applying transformations dynamically...")

train_loader = DataLoader(AugmentedHFImageDataset(hf_dataset["train"], train_preprocess), batch_size=32, shuffle=True)
val_loader = DataLoader(AugmentedHFImageDataset(hf_dataset["validation"], eval_preprocess), batch_size=32, shuffle=False)
test_loader = DataLoader(AugmentedHFImageDataset(hf_dataset["test"], eval_preprocess), batch_size=32, shuffle=False)

# 3. BUILD MODEL
print("Building ResNet50...")
model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
for param in model.parameters():
    param.requires_grad = False # Freeze base

# Add custom head
model.fc = nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.fc.parameters(), lr=0.001, weight_decay=1e-4)

from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score

# ==========================================
# 4. TRAINING & DUAL EVALUATION LOOP
# ==========================================

# Helper function to evaluate any dataloader
def evaluate_model(loader, eval_model):
    eval_model.eval()
    all_preds, all_labels = [], []

    with torch.no_grad():
        for batch in loader:
            inputs = batch["pixel_values"].to(device)
            labels = batch["label"].to(device)

            outputs = eval_model(inputs)
            _, predicted = torch.max(outputs.data, 1)

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    bal_acc = balanced_accuracy_score(all_labels, all_preds)
    macro_f1 = f1_score(all_labels, all_preds, average='macro')

    return acc, bal_acc, macro_f1

# --- Main Loop ---
EPOCHS = 10
best_val_macro_f1 = 0.0

print(f"Starting training for {EPOCHS} epochs...")
for epoch in range(EPOCHS):
    # --- TRAINING PHASE ---
    model.train()
    running_loss = 0.0

    for batch in train_loader:
        inputs, labels = batch["pixel_values"].to(device), batch["label"].to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    # --- EVALUATION PHASE ---
    # 1. Evaluate on Training Data (Snapshot of current knowledge)
    train_acc, train_bal_acc, train_macro_f1 = evaluate_model(train_loader, model)

    # 2. Evaluate on Validation Data (Test on unseen data)
    val_acc, val_bal_acc, val_macro_f1 = evaluate_model(val_loader, model)

    # 3. Evaluate on Test Data (Test on seen data)
    test_acc, test_bal_acc, test_macro_f1 = evaluate_model(test_loader, model)

    # Print the detailed epoch report side-by-side
    print(f"\nEpoch {epoch+1}/{EPOCHS} Summary | Loss: {running_loss/len(train_loader):.4f}")
    print(f"  [TRAIN] Acc: {train_acc:.4f} | Bal Acc: {train_bal_acc:.4f} | Macro F1: {train_macro_f1:.4f}")
    print(f"  [VALID] Acc: {val_acc:.4f} | Bal Acc: {val_bal_acc:.4f} | Macro F1: {val_macro_f1:.4f}")
    print(f"  [TEST]  Acc: {test_acc:.4f} | Bal Acc: {test_bal_acc:.4f} | Macro F1: {test_macro_f1:.4f}")

    # Save checkpoint based on VALIDATION Macro F1
    if val_macro_f1 > best_val_macro_f1:
        best_val_macro_f1 = val_macro_f1
        torch.save(model.state_dict(), "best_resnet50.pt")
        print("  🌟 Checkpoint: New best model saved (based on Validation Macro F1)!")

# 5. CONFUSION MATRIX
print("\nGenerating Confusion Matrix...")
model.load_state_dict(torch.load("best_resnet50.pt")) # Load best weights
model.eval()

all_preds, all_labels = [], []
with torch.no_grad():
    for batch in val_loader:
        inputs, labels = batch["pixel_values"].to(device), batch["label"].to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('End-to-End Validation Confusion Matrix')
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.xticks(rotation=45, ha='right'); plt.tight_layout(); plt.show()

import torch.nn.functional as F

# ==========================================
# STEP 6: TEST ON SINGLE IMAGE + SALIENCY + GRAD-CAM
# ==========================================
print("\nGenerating Prediction, Saliency, and Grad-CAM...")

# 1. Grab a single example
sample_idx = 24
raw_sample = hf_dataset['test'][sample_idx]
true_label_text = class_names[raw_sample['label']]

# 2. Prepare the image and track gradients
img_tensor = eval_preprocess(raw_sample['image'].convert('RGB')).unsqueeze(0).to(device)
img_tensor.requires_grad_()

# 3. Setup PyTorch Hooks for Grad-CAM
activations = []
gradients = []

def forward_hook(module, input, output):
    activations.append(output)

def backward_hook(module, grad_input, grad_output):
    gradients.append(grad_output[0])

# Attach the hooks to the final convolutional block in ResNet50
target_layer = model.layer4[-1]
f_hook = target_layer.register_forward_hook(forward_hook)
b_hook = target_layer.register_full_backward_hook(backward_hook)

# 4. Forward Pass
model.eval()
model.zero_grad()
outputs = model(img_tensor)

probabilities = F.softmax(outputs[0], dim=0)
pred_prob, pred_idx = torch.max(probabilities, 0)
pred_class = class_names[pred_idx.item()]

# 5. Backward Pass
score = outputs[0][pred_idx]
score.backward()

# ==========================================
# PROCESS SALIENCY MAP
# ==========================================
saliency_map, _ = torch.max(img_tensor.grad.data.abs(), dim=1)
saliency_map = saliency_map.squeeze().cpu().numpy()

# ==========================================
# PROCESS GRAD-CAM
# ==========================================
captured_grads = gradients[0]
captured_acts = activations[0]

weights = torch.mean(captured_grads, dim=[2, 3], keepdim=True)
cam = torch.sum(weights * captured_acts, dim=1, keepdim=True)
cam = F.relu(cam)

cam = F.interpolate(cam, size=(224, 224), mode='bilinear', align_corners=False)
cam = cam.squeeze().cpu().detach().numpy()
cam = (cam - cam.min()) / (cam.max() - cam.min())

f_hook.remove()
b_hook.remove()

# ==========================================
# PROCESS ORIGINAL IMAGE (FIX COLORS)
# ==========================================
# Un-normalize the tensor to restore the true colors
mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

# Reverse the math and clamp values between 0 and 1
unnormalized_tensor = sample['pixel_values'].cpu() * std + mean
unnormalized_tensor = torch.clamp(unnormalized_tensor, 0, 1)

# Convert to a human-readable image
raw_image = transforms.ToPILImage()(unnormalized_tensor)

# ==========================================
# VISUALIZE EVERYTHING
# ==========================================
plt.figure(figsize=(18, 5))

# Plot 1: True Original Image
plt.subplot(1, 3, 1)
plt.imshow(raw_image)
plt.title(f"Predicted: {pred_class} ({pred_prob.item()*100:.2f}%)\nActual: {true_label_text}",
          color='green' if pred_class == true_label_text else 'red', fontsize=14)
plt.axis('off')

# Plot 2: Saliency Map
plt.subplot(1, 3, 2)
plt.imshow(saliency_map, cmap='hot')
plt.title("Saliency Map\n(Pixel-Level Importance)", fontsize=14)
plt.axis('off')

# Plot 3: Grad-CAM Overlay
plt.subplot(1, 3, 3)
plt.imshow(raw_image)
plt.imshow(cam, cmap='jet', alpha=0.5)
plt.title("Grad-CAM\n(Regional Feature Importance)", fontsize=14)
plt.axis('off')

plt.tight_layout()
plt.show()