# -*- coding: utf-8 -*-
"""rsmitsd_cnn_pytorch.ipynb (augmentation clone)

Automatically generated by Colab.

This version adds stronger augmentation before the ResNet50 classifier so it can be compared directly to the non-augmentation baseline.

Original file is located at
    https://colab.research.google.com/drive/1ux4LiyKizRwanve9gta6YmQ_R8gDeviM
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from torch.utils.data import DataLoader
from datasets import load_from_disk
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score, balanced_accuracy_score, f1_score
import numpy as np
import os

# 1. SETUP & DATA LOADING
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

print("Downloading dataset...")
path = kagglehub.dataset_download("phantrntngvyk64cntt/processed-rsitmd-256-clean")

print("Path to dataset files:", path)
hf_dataset = load_from_disk(path)

# Extract class names safely
try:
    class_names = hf_dataset['train'].features['label'].names
except AttributeError:
    unique_labels = set(hf_dataset['train']['label'])
    class_names = [str(label) for label in sorted(unique_labels)]
num_classes = len(class_names)

# 2. PREPROCESSING
# NOTE: Augmentation clone — only the train-time image pipeline changes versus the non-augmentation baseline.
preprocess = transforms.Compose([
    transforms.RandomResizedCrop((224, 224), scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.RandomPerspective(distortion_scale=0.15, p=0.25),
    transforms.ColorJitter(brightness=0.18, contrast=0.18, saturation=0.12, hue=0.04),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def transform_dataset(examples):
    examples["pixel_values"] = [preprocess(img.convert("RGB")) for img in examples["image"]]
    return examples

print("Applying transformations...")
cache_dir = "/kaggle/working/hf_cache"
os.makedirs(cache_dir, exist_ok=True)
cache_files = {split_name: f"{cache_dir}/rsitmd_{split_name}_cache.arrow" for split_name in hf_dataset.keys()}
hf_dataset = hf_dataset.map(transform_dataset, batched=True, load_from_cache_file=False, cache_file_names=cache_files)
hf_dataset.set_format(type="torch", columns=["pixel_values", "label"])

train_loader = DataLoader(hf_dataset["train"], batch_size=32, shuffle=True)
val_loader = DataLoader(hf_dataset["validation"], batch_size=32, shuffle=False)
test_loader = DataLoader(hf_dataset["test"], batch_size=32, shuffle=False)

# 3. BUILD MODEL
print("Building ResNet50...")
model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
for param in model.parameters():
    param.requires_grad = False # Freeze base

# Add custom head
model.fc = nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

# 4. METRICS & TRAINING LOOP WITH LIVE CURVES
import time
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score

@torch.no_grad()
def run_eval(model, loader, device, criterion):
    model.eval()
    ys, ps = [], []
    total_loss, n = 0.0, 0
    for batch in loader:
        inputs = batch["pixel_values"].to(device, non_blocking=True)
        labels = batch["label"].to(device, non_blocking=True)
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        _, preds = torch.max(outputs, 1)
        ys.extend(labels.cpu().numpy().tolist())
        ps.extend(preds.cpu().numpy().tolist())
        bs = labels.size(0)
        total_loss += loss.item() * bs
        n += bs
    return {
        "loss": total_loss / max(n, 1),
        "acc": accuracy_score(ys, ps),
        "balanced_acc": balanced_accuracy_score(ys, ps),
        "macro_f1": f1_score(ys, ps, average="macro", zero_division=0)
    }

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    ys, ps = [], []
    total_loss, n = 0.0, 0
    for batch in loader:
        inputs = batch["pixel_values"].to(device, non_blocking=True)
        labels = batch["label"].to(device, non_blocking=True)
        
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        _, preds = torch.max(outputs, 1)
        ys.extend(labels.cpu().numpy().tolist())
        ps.extend(preds.cpu().numpy().tolist())
        bs = labels.size(0)
        total_loss += loss.item() * bs
        n += bs
    return {
        "loss": total_loss / max(n, 1),
        "acc": accuracy_score(ys, ps),
        "balanced_acc": balanced_accuracy_score(ys, ps),
        "macro_f1": f1_score(ys, ps, average="macro", zero_division=0)
    }

def update_learning_curves(history, output_path="live_learning_curves.png"):
    if not history: return
    ep_range = [h["epoch"] for h in history]
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    ax1.plot(ep_range, [h.get("train_loss") for h in history], label="Train", marker="o")
    ax1.plot(ep_range, [h.get("val_loss") for h in history], label="Val", marker="o")
    ax1.set_title("Loss over Epochs")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("Loss")
    ax1.legend()
    ax1.grid(True)
    
    ax2.plot(ep_range, [h.get("train_macro_f1") for h in history], label="Train", marker="o")
    ax2.plot(ep_range, [h.get("val_macro_f1") for h in history], label="Val", marker="o")
    ax2.set_title("Macro F1 over Epochs")
    ax2.set_xlabel("Epoch")
    ax2.set_ylabel("Macro F1")
    ax2.legend()
    ax2.grid(True)
    
    plt.tight_layout()
    fig.savefig(output_path, dpi=150)
    plt.close(fig)

EPOCHS = 50
EARLY_STOP_PATIENCE = 8
best_f1 = 0.0
no_improve = 0
history = []

print(f"Starting training for {EPOCHS} epochs with Live Learning Curves...")
for epoch in range(1, EPOCHS + 1):
    t0 = time.time()
    tr_metrics = train_one_epoch(model, train_loader, optimizer, criterion, device)
    va_metrics = run_eval(model, val_loader, device, criterion)
    epoch_time = time.time() - t0
    
    row = {"epoch": epoch, "epoch_time_sec": epoch_time}
    row.update({f"train_{k}": v for k, v in tr_metrics.items()})
    row.update({f"val_{k}": v for k, v in va_metrics.items()})
    history.append(row)
    
    # Save chart incrementally (live update)
    update_learning_curves(history, output_path="live_learning_curves.png")
    
    print(f"Epoch {epoch:02d}/{EPOCHS} | Time: {epoch_time:.1f}s")
    print(f"  [Train] Loss: {tr_metrics['loss']:.4f} - Acc: {tr_metrics['acc']:.4f} - BalAcc: {tr_metrics['balanced_acc']:.4f} - F1: {tr_metrics['macro_f1']:.4f}")
    print(f"  [Val]   Loss: {va_metrics['loss']:.4f} - Acc: {va_metrics['acc']:.4f} - BalAcc: {va_metrics['balanced_acc']:.4f} - F1: {va_metrics['macro_f1']:.4f}")

    if va_metrics['macro_f1'] > best_f1:
        best_f1 = va_metrics['macro_f1']
        no_improve = 0
        torch.save(model.state_dict(), "best_resnet50.pt")
        print("  -> Checkpoint: New best model saved (based on Val F1)!")
    else:
        no_improve += 1
        if no_improve >= EARLY_STOP_PATIENCE:
            print(f"Early stopping at epoch {epoch}")
            break

# 5. TEST EVALUATION & CONFUSION MATRIX
print("\nEvaluating on Test Set...")
model.load_state_dict(torch.load("best_resnet50.pt")) # Load best weights
test_metrics = run_eval(model, test_loader, device, criterion)
print(f"Final Test Accuracy: {test_metrics['acc']:.4f}")
print(f"Final Test Balanced Accuracy: {test_metrics['balanced_acc']:.4f}")
print(f"Final Test Macro F1: {test_metrics['macro_f1']:.4f}")

model.eval()
all_preds, all_labels = [], []
with torch.no_grad():
    for batch in test_loader:
        inputs, labels = batch["pixel_values"].to(device), batch["label"].to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print("\nGenerating Confusion Matrix for Test Set...")
print(f"Test Balanced Accuracy (recomputed): {balanced_accuracy_score(all_labels, all_preds):.4f}")
cm = confusion_matrix(all_labels, all_preds, labels=range(len(class_names)))
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('End-to-End Test Confusion Matrix')
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.xticks(rotation=45, ha='right'); plt.tight_layout(); plt.savefig("cnn_frozen_confusion_matrix.png"); plt.show()

# 5.5 SAVE REPORT
import json
from sklearn.metrics import classification_report
cls_report = classification_report(all_labels, all_preds, labels=range(len(class_names)), target_names=class_names, zero_division=0, output_dict=True)
report_path = "cnn_frozen_report.json"
with open(report_path, "w", encoding="utf-8") as f:
    json.dump({
        "test_metrics": test_metrics,
        "classification_report": cls_report,
        "history": history
    }, f, indent=4)
print(f"✅ Saved training report to {report_path}")

import torch.nn.functional as F

# ==========================================
# STEP 6: TEST ON SINGLE IMAGE + SALIENCY + GRAD-CAM
# ==========================================
print("\nGenerating Prediction, Saliency, and Grad-CAM...")

# 1. Grab a single example
sample_idx = 24
sample = hf_dataset['validation'][sample_idx]
true_label_text = class_names[sample['label'].item()]

# 2. Prepare the image and track gradients
img_tensor = sample['pixel_values'].unsqueeze(0).to(device)
img_tensor.requires_grad_()

# 3. Setup PyTorch Hooks for Grad-CAM
activations = []
gradients = []

def forward_hook(module, input, output):
    activations.append(output)

def backward_hook(module, grad_input, grad_output):
    gradients.append(grad_output[0])

# Attach the hooks to the final convolutional block in ResNet50
target_layer = model.layer4[-1]
f_hook = target_layer.register_forward_hook(forward_hook)
b_hook = target_layer.register_full_backward_hook(backward_hook)

# 4. Forward Pass
model.eval()
model.zero_grad()
outputs = model(img_tensor)

probabilities = F.softmax(outputs[0], dim=0)
pred_prob, pred_idx = torch.max(probabilities, 0)
pred_class = class_names[pred_idx.item()]

# 5. Backward Pass
score = outputs[0][pred_idx]
score.backward()

# ==========================================
# PROCESS SALIENCY MAP
# ==========================================
saliency_map, _ = torch.max(img_tensor.grad.data.abs(), dim=1)
saliency_map = saliency_map.squeeze().cpu().numpy()

# ==========================================
# PROCESS GRAD-CAM
# ==========================================
captured_grads = gradients[0]
captured_acts = activations[0]

weights = torch.mean(captured_grads, dim=[2, 3], keepdim=True)
cam = torch.sum(weights * captured_acts, dim=1, keepdim=True)
cam = F.relu(cam)

cam = F.interpolate(cam, size=(224, 224), mode='bilinear', align_corners=False)
cam = cam.squeeze().cpu().detach().numpy()
cam = (cam - cam.min()) / (cam.max() - cam.min())

f_hook.remove()
b_hook.remove()

# ==========================================
# PROCESS ORIGINAL IMAGE (FIX COLORS)
# ==========================================
# Un-normalize the tensor to restore the true colors
mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

# Reverse the math and clamp values between 0 and 1
unnormalized_tensor = sample['pixel_values'].cpu() * std + mean
unnormalized_tensor = torch.clamp(unnormalized_tensor, 0, 1)

# Convert to a human-readable image
raw_image = transforms.ToPILImage()(unnormalized_tensor)

# ==========================================
# VISUALIZE EVERYTHING
# ==========================================
plt.figure(figsize=(18, 5))

# Plot 1: True Original Image
plt.subplot(1, 3, 1)
plt.imshow(raw_image)
plt.title(f"Predicted: {pred_class} ({pred_prob.item()*100:.2f}%)\nActual: {true_label_text}",
          color='green' if pred_class == true_label_text else 'red', fontsize=14)
plt.axis('off')

# Plot 2: Saliency Map
plt.subplot(1, 3, 2)
plt.imshow(saliency_map, cmap='hot')
plt.title("Saliency Map\n(Pixel-Level Importance)", fontsize=14)
plt.axis('off')

# Plot 3: Grad-CAM Overlay
plt.subplot(1, 3, 3)
plt.imshow(raw_image)
plt.imshow(cam, cmap='jet', alpha=0.5)
plt.title("Grad-CAM\n(Regional Feature Importance)", fontsize=14)
plt.axis('off')

plt.tight_layout()
plt.show()