# -*- coding: utf-8 -*-
"""rsitmd_svm_feature_pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PhHGIBPoVZ2HQBvV6bs_1Ur-fwSyz1B2
"""

# ==========================================
# PYTORCH EXTRACTOR + SVM
# ==========================================
import torch
import torch.nn as nn
from torchvision import models, transforms
from torch.utils.data import DataLoader
from datasets import load_from_disk
import kagglehub
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import joblib
import json

import os
import datasets

# Redirect all Hugging Face temporary/cache files to Kaggle's writable folder
os.environ['HF_DATASETS_CACHE'] = '/kaggle/working/hf_cache'
datasets.config.HF_DATASETS_CACHE = '/kaggle/working/hf_cache'

# 1. SETUP & DATA LOADING
device = torch.device("cuda" if torch.cuda.is_available() else "gpu")
print(f"Using device: {device}")

print("Downloading dataset...")
path = kagglehub.dataset_download("phantrntngvyk64cntt/processed-rsitmd-256-clean")
hf_dataset = load_from_disk(path)

try:
    class_names = hf_dataset['train'].features['label'].names
except AttributeError:
    unique_labels = set(hf_dataset['train']['label'])
    class_names = [str(label) for label in sorted(unique_labels)]

preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def transform_dataset(examples):
    examples["pixel_values"] = [preprocess(img.convert("RGB")) for img in examples["image"]]
    return examples

print("Applying transformations...")

# Ensure writable temporary directories exist
writable_tmp_dir = '/kaggle/working/tmp'
cache_dir = '/kaggle/working/hf_cache'
os.makedirs(writable_tmp_dir, exist_ok=True)
os.makedirs(cache_dir, exist_ok=True)
os.environ['TMPDIR'] = writable_tmp_dir

# 1. Dynamically create a cache path for EVERY split inside the dataset
cache_files = {
    split_name: f"{cache_dir}/rsitmd_{split_name}_cache.arrow"
    for split_name in hf_dataset.keys()
}

print(f"Saving caches to: {cache_files}")

# 2. Pass the dynamically generated dictionary
hf_dataset = hf_dataset.map(
    transform_dataset,
    batched=True,
    load_from_cache_file=False,
    cache_file_names=cache_files
)

hf_dataset.set_format(type="torch", columns=["pixel_values", "label"])

# 3. Create your DataLoaders (and grab the test one too!)
train_loader = DataLoader(hf_dataset["train"], batch_size=32, shuffle=False)
val_loader = DataLoader(hf_dataset["validation"], batch_size=32, shuffle=False)

if "test" in hf_dataset:
    test_loader = DataLoader(hf_dataset["test"], batch_size=32, shuffle=False)
    print("✅ Created DataLoaders for train, validation, AND test!")
else:
    print("✅ Created DataLoaders for train and validation!")

# 3. BUILD EXTRACTOR
print("Building ResNet50 Extractor...")
extractor = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
extractor.fc = nn.Identity() # Remove the final layer!
extractor = extractor.to(device)
extractor.eval()

# 4. EXTRACT FEATURES
def extract_features(dataloader, model_extractor):
    features_list, labels_list = [], []
    with torch.no_grad():
        for batch in dataloader:
            inputs = batch["pixel_values"].to(device)
            labels = batch["label"].numpy()
            features = model_extractor(inputs).cpu().numpy()
            features_list.append(features)
            labels_list.extend(labels)
    return np.vstack(features_list), np.array(labels_list)

print("Extracting features (this might take a minute)...")
X_train, y_train = extract_features(train_loader, extractor)
X_val, y_val = extract_features(val_loader, extractor)

# 5. TRAIN SVM
print("Training SVM...")
svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train, y_train)

# 6. EVALUATION & CONFUSION MATRIX
print("\nEvaluating...")
y_pred = svm.predict(X_val)
print("SVM Accuracy:", accuracy_score(y_val, y_pred))
print("Classification Report:\n", classification_report(y_val, y_pred, target_names=class_names))

cm = confusion_matrix(y_val, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', xticklabels=class_names, yticklabels=class_names)
plt.title('SVM Validation Confusion Matrix')
plt.xlabel('SVM Predicted'); plt.ylabel('Actual')
plt.xticks(rotation=45, ha='right'); plt.tight_layout(); plt.show()

# 7. SAVE MODELS & METADATA
print("\nSaving deployable files...")
joblib.dump(svm, 'svm_model.joblib')
torch.save(extractor.state_dict(), "resnet50_extractor.pt")

with open("label_mapping.json", "w") as f:
    json.dump({"id2label": {int(i): name for i, name in enumerate(class_names)}}, f, indent=4)
print("✅ Saved: svm_model.joblib, resnet50_extractor.pt, label_mapping.json")

import torch.nn.functional as F

# ==========================================
# 8. TEST ON SINGLE IMAGE + FEATURE ATTENTION
# ==========================================
sample = hf_dataset['validation'][0]
img_tensor = sample['pixel_values'].unsqueeze(0).to(device)
true_label_text = class_names[sample['label'].item()]

# 1. Setup a Hook to eavesdrop on ResNet50's final layer
activations = []
def forward_hook(module, input, output):
    activations.append(output)

# Attach hook to the final convolutional block
target_layer = extractor.layer4[-1]
f_hook = target_layer.register_forward_hook(forward_hook)

# 2. Extract feature and predict with SVM
with torch.no_grad(): # No gradients needed!
    single_feature = extractor(img_tensor).cpu().numpy()

pred_idx = svm.predict(single_feature)[0]
pred_prob = np.max(svm.predict_proba(single_feature)) * 100
pred_class = class_names[pred_idx]

# 3. Process the generalized Feature Attention Map
# Take the mean of the feature maps across all channels to see general attention
captured_acts = activations[0]
heatmap = torch.mean(captured_acts, dim=1, keepdim=True)
heatmap = F.relu(heatmap) # Keep only positive attention

# Resize heatmap to match the 224x224 image
heatmap = F.interpolate(heatmap, size=(224, 224), mode='bilinear', align_corners=False)
heatmap = heatmap.squeeze().cpu().numpy()
heatmap = (heatmap - heatmap.min()) / (heatmap.max() - heatmap.min()) # Normalize

f_hook.remove() # Clean up the hook

# 4. Un-normalize the tensor to restore the true colors of the original image
mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
unnormalized_tensor = sample['pixel_values'].cpu() * std + mean
unnormalized_tensor = torch.clamp(unnormalized_tensor, 0, 1)
raw_image = transforms.ToPILImage()(unnormalized_tensor)

# ==========================================
# VISUALIZE BOTH IMAGES
# ==========================================
plt.figure(figsize=(12, 5))

# Plot 1: True Original Image
plt.subplot(1, 2, 1)
plt.imshow(raw_image)
plt.title(f"SVM Predicted: {pred_class} ({pred_prob:.2f}%)\nActual: {true_label_text}",
          color='green' if pred_class == true_label_text else 'red', fontsize=14)
plt.axis('off')

# Plot 2: Extractor Attention Map
plt.subplot(1, 2, 2)
plt.imshow(raw_image)
plt.imshow(heatmap, cmap='jet', alpha=0.5) # Overlay the heatmap
plt.title("ResNet50 Attention Map\n(What the Extractor focuses on)", fontsize=14)
plt.axis('off')

plt.tight_layout()
plt.show()