# -*- coding: utf-8 -*-
"""rsitmd_svm_feature_pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOFHSm4NuCqdzL_Z0ee-nHvojqHQyx4p
"""

# ==========================================
# PYTORCH EXTRACTOR + SVM
# ==========================================
import os
import time
import json
import joblib

import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import seaborn as sns
from datasets import load_from_disk
from sklearn.model_selection import learning_curve
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, balanced_accuracy_score, classification_report, confusion_matrix, f1_score
from torchvision import models, transforms
from torch.utils.data import DataLoader
import kagglehub

# 1. SETUP & DATA LOADING
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

print("Downloading dataset...")
path = kagglehub.dataset_download("phantrntngvyk64cntt/processed-rsitmd-256-clean")
hf_dataset = load_from_disk(path)
output_dir = "outputs_svm_non_au"
os.makedirs(output_dir, exist_ok=True)

try:
    class_names = hf_dataset['train'].features['label'].names
except AttributeError:
    unique_labels = set(hf_dataset['train']['label'])
    class_names = [str(label) for label in sorted(unique_labels)]

# 2. PREPROCESSING
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def transform_dataset(examples):
    # 1. Create the tensor versions of the images
    examples["pixel_values"] = [preprocess(img.convert("RGB")) for img in examples["image"]]

    # 2. Delete the raw PIL images so the DataLoader doesn't try to batch them
    del examples["image"]

    return examples

# Apply it exactly as before
hf_dataset.set_transform(transform_dataset)

print("Applying transformations dynamically...")

# Replace .map() and .set_format() with .set_transform()
hf_dataset.set_transform(transform_dataset)

# Your DataLoaders remain exactly the same
train_loader = DataLoader(hf_dataset["train"], batch_size=32, shuffle=True)
val_loader = DataLoader(hf_dataset["validation"], batch_size=32, shuffle=False)
test_loader = DataLoader(hf_dataset["test"], batch_size=32, shuffle=False)

# 3. BUILD EXTRACTOR
print("Building ResNet50 Extractor...")
extractor = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
extractor.fc = nn.Identity() # Remove the final layer!
extractor = extractor.to(device)
extractor.eval()
if device.type == "cuda":
    torch.cuda.reset_peak_memory_stats()

# 4. EXTRACT FEATURES
def extract_features(dataloader, model_extractor):
    features_list, labels_list = [], []
    with torch.no_grad():
        for batch in dataloader:
            inputs = batch["pixel_values"].to(device)
            labels = batch["label"].numpy()
            features = model_extractor(inputs).cpu().numpy()
            features_list.append(features)
            labels_list.extend(labels)
    return np.vstack(features_list), np.array(labels_list)

print("Extracting features (this might take a minute)...")
X_train, y_train = extract_features(train_loader, extractor)
X_val, y_val = extract_features(val_loader, extractor)
X_test, y_test = extract_features(test_loader, extractor)

# 5. TRAIN SVM
print("Training SVM...")
svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train, y_train)

# 6. EVALUATION & CONFUSION MATRIX
print("\nEvaluating...")
start_inf = time.time()
y_pred = svm.predict(X_val)
inference_sec_per_batch = time.time() - start_inf
overall_acc = accuracy_score(y_val, y_pred)
bal_acc = balanced_accuracy_score(y_val, y_pred)
macro_f1 = f1_score(y_val, y_pred, average='macro', zero_division=0)
ms_per_batch = 1000.0 * inference_sec_per_batch
images_per_sec = (len(X_val) / inference_sec_per_batch) if inference_sec_per_batch > 0 else None
print(f"Overall Accuracy: {overall_acc:.4f}")
print(f"Balanced Accuracy: {bal_acc:.4f}")
print(f"Macro F1: {macro_f1:.4f}")
gpu_peak_mb = (torch.cuda.max_memory_allocated(device) / (1024 ** 2)) if device.type == "cuda" else None
print(f"Inference Time: {ms_per_batch:.4f} ms/batch | {images_per_sec:.4f} images/sec")
print(f"GPU Peak Memory: {gpu_peak_mb:.4f} MB" if gpu_peak_mb is not None else "GPU Peak Memory: N/A (CPU)")
print("Classification Report:\n", classification_report(y_val, y_pred, target_names=class_names, digits=4, zero_division=0))

cm = confusion_matrix(y_val, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', xticklabels=class_names, yticklabels=class_names)
plt.title('SVM Validation Confusion Matrix')
plt.xlabel('SVM Predicted'); plt.ylabel('Actual')
plt.xticks(rotation=45, ha='right'); plt.tight_layout()
cm_path = os.path.join(output_dir, 'confusion_matrix.png')
plt.savefig(cm_path, dpi=200, bbox_inches='tight')
plt.show()

# 7. SAVE MODELS & METADATA
print("\nSaving deployable files...")
joblib.dump(svm, 'svm_model.joblib')
torch.save(extractor.state_dict(), "resnet50_extractor.pt")

with open("label_mapping.json", "w") as f:
    json.dump({"id2label": {int(i): name for i, name in enumerate(class_names)}}, f, indent=4)

report = {
    "model": "SVM + ResNet50 Features",
    "metrics": {
        "accuracy": float(overall_acc),
        "balanced_accuracy": float(bal_acc),
        "macro_f1": float(macro_f1),
    },
    "timing": {
        "inference": {
            "ms_per_batch": float(ms_per_batch),
            "images_per_sec": float(images_per_sec) if images_per_sec is not None else None,
        },
        "training_time_sec": None,
    },
    "gpu_peak_mb": float(gpu_peak_mb) if gpu_peak_mb is not None else None,
    "artifacts": {
        "confusion_matrix": cm_path,
        "learning_curves": learning_curve_path,
    },
}
with open(os.path.join(output_dir, "svm_report.json"), "w") as f:
    json.dump(report, f, indent=2)
print("✅ Saved: svm_model.joblib, resnet50_extractor.pt, label_mapping.json, svm_report.json")

import torch.nn.functional as F

# 6b. LEARNING CURVE FOR SVM
print("Generating learning curves...")
train_sizes, train_scores, val_scores = learning_curve(
    svm,
    X_train,
    y_train,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=3,
    scoring='f1_macro',
    n_jobs=-1,
)
train_mean = np.mean(train_scores, axis=1)
train_std = np.std(train_scores, axis=1)
val_mean = np.mean(val_scores, axis=1)
val_std = np.std(val_scores, axis=1)
plt.figure(figsize=(8, 5))
plt.plot(train_sizes, train_mean, marker='o', label='Training macro F1')
plt.fill_between(train_sizes, train_mean-train_std, train_mean+train_std, alpha=0.15)
plt.plot(train_sizes, val_mean, marker='o', label='Cross-val macro F1')
plt.fill_between(train_sizes, val_mean-val_std, val_mean+val_std, alpha=0.15)
plt.xlabel('Training samples')
plt.ylabel('Macro F1')
plt.title('SVM Learning Curves')
plt.legend()
plt.tight_layout()
learning_curve_path = os.path.join(output_dir, 'learning_curves.png')
plt.savefig(learning_curve_path, dpi=200, bbox_inches='tight')
plt.show()

# ==========================================
# 8. TEST ON SINGLE IMAGE + FEATURE ATTENTION
# ==========================================
sample = hf_dataset['test'][450]
img_tensor = sample['pixel_values'].unsqueeze(0).to(device)
true_label_text = class_names[sample['label']]

# 1. Setup a Hook to eavesdrop on ResNet50's final layer
activations = []
def forward_hook(module, input, output):
    activations.append(output)

# Attach hook to the final convolutional block
target_layer = extractor.layer4[-1]
f_hook = target_layer.register_forward_hook(forward_hook)

# 2. Extract feature and predict with SVM
with torch.no_grad(): # No gradients needed!
    single_feature = extractor(img_tensor).cpu().numpy()

pred_idx = svm.predict(single_feature)[0]
pred_prob = np.max(svm.predict_proba(single_feature)) * 100
pred_class = class_names[pred_idx]

# 3. Process the generalized Feature Attention Map
# Take the mean of the feature maps across all channels to see general attention
captured_acts = activations[0]
heatmap = torch.mean(captured_acts, dim=1, keepdim=True)
heatmap = F.relu(heatmap) # Keep only positive attention

# Resize heatmap to match the 224x224 image
heatmap = F.interpolate(heatmap, size=(224, 224), mode='bilinear', align_corners=False)
heatmap = heatmap.squeeze().cpu().numpy()
heatmap = (heatmap - heatmap.min()) / (heatmap.max() - heatmap.min()) # Normalize

f_hook.remove() # Clean up the hook

# 4. Un-normalize the tensor to restore the true colors of the original image
mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
unnormalized_tensor = sample['pixel_values'].cpu() * std + mean
unnormalized_tensor = torch.clamp(unnormalized_tensor, 0, 1)
raw_image = transforms.ToPILImage()(unnormalized_tensor)

# ==========================================
# VISUALIZE BOTH IMAGES
# ==========================================
plt.figure(figsize=(12, 5))

# Plot 1: True Original Image
plt.subplot(1, 2, 1)
plt.imshow(raw_image)
plt.title(f"SVM Predicted: {pred_class} ({pred_prob:.2f}%)\nActual: {true_label_text}",
          color='green' if pred_class == true_label_text else 'red', fontsize=14)
plt.axis('off')

# Plot 2: Extractor Attention Map
plt.subplot(1, 2, 2)
plt.imshow(raw_image)
plt.imshow(heatmap, cmap='jet', alpha=0.5) # Overlay the heatmap
plt.title("ResNet50 Attention Map\n(What the Extractor focuses on)", fontsize=14)
plt.axis('off')

plt.tight_layout()
plt.show()