# -*- coding: utf-8 -*-
"""rsmitsd_cnn_pytorch_final (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SNp6mRZX8VFbYGl9y3yz7RaAXsO1B36V
"""

# ==========================================
# FULL SCRIPT: PYTORCH END-TO-END DEEP LEARNING
# ==========================================
import os
import time
import json
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from torch.utils.data import DataLoader
from datasets import load_from_disk
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score

# 1. SETUP & DATA LOADING
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

print("Downloading dataset...")
path = kagglehub.dataset_download("phantrntngvyk64cntt/processed-rsitmd-256-clean")
output_dir = "outputs_cnn_frozen_non_au"
os.makedirs(output_dir, exist_ok=True)

print("Path to dataset files:", path)
hf_dataset = load_from_disk(path)

# Extract class names safely
try:
    class_names = hf_dataset['train'].features['label'].names
except AttributeError:
    unique_labels = set(hf_dataset['train']['label'])
    class_names = [str(label) for label in sorted(unique_labels)]
num_classes = len(class_names)

# 2. PREPROCESSING
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def transform_dataset(examples):
    # 1. Create the tensor versions of the images
    examples["pixel_values"] = [preprocess(img.convert("RGB")) for img in examples["image"]]

    # 2. Delete the raw PIL images so the DataLoader doesn't try to batch them
    del examples["image"]

    return examples

# Apply it exactly as before
hf_dataset.set_transform(transform_dataset)

print("Applying transformations dynamically...")

# Replace .map() and .set_format() with .set_transform()
hf_dataset.set_transform(transform_dataset)

# Your DataLoaders remain exactly the same
train_loader = DataLoader(hf_dataset["train"], batch_size=32, shuffle=True)
val_loader = DataLoader(hf_dataset["validation"], batch_size=32, shuffle=False)
test_loader = DataLoader(hf_dataset["test"], batch_size=32, shuffle=False)

# 3. BUILD MODEL
print("Building ResNet50...")
model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
for param in model.parameters():
    param.requires_grad = False # Freeze base

# Add custom head
model.fc = nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

if device.type == "cuda":
    torch.cuda.reset_peak_memory_stats()

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.fc.parameters(), lr=0.001, weight_decay=0.0)

from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score


def measure_inference_speed(model, loader, device, warmup=5):
    model.eval()
    times = []
    it = iter(loader)
    with torch.no_grad():
        for _ in range(warmup):
            try:
                batch = next(it)
            except StopIteration:
                break
            inputs = batch["pixel_values"].to(device)
            _ = model(inputs)
        for batch in loader:
            inputs = batch["pixel_values"].to(device)
            if device.type == "cuda":
                torch.cuda.synchronize()
            t0 = torch.cuda.Event(enable_timing=True) if device.type == "cuda" else None
            if device.type == "cuda":
                start = torch.cuda.Event(enable_timing=True)
                end = torch.cuda.Event(enable_timing=True)
                start.record()
                _ = model(inputs)
                end.record()
                torch.cuda.synchronize()
                times.append(start.elapsed_time(end) / 1000.0)
            else:
                import time as _time
                t0 = _time.time()
                _ = model(inputs)
                times.append(_time.time() - t0)
    if not times:
        return {"ms_per_batch": None, "images_per_sec": None}
    ms_per_batch = float(np.mean(times)) * 1000.0
    images_per_sec = float(loader.batch_size / np.mean(times))
    return {"ms_per_batch": ms_per_batch, "images_per_sec": images_per_sec}

# ==========================================
# 4. TRAINING & DUAL EVALUATION LOOP
# ==========================================

# Helper function to evaluate any dataloader
def evaluate_model(loader, eval_model):
    eval_model.eval()
    all_preds, all_labels = [], []

    with torch.no_grad():
        for batch in loader:
            inputs = batch["pixel_values"].to(device)
            labels = batch["label"].to(device)

            outputs = eval_model(inputs)
            _, predicted = torch.max(outputs.data, 1)

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    bal_acc = balanced_accuracy_score(all_labels, all_preds)
    macro_f1 = f1_score(all_labels, all_preds, average='macro')

    return acc, bal_acc, macro_f1

# --- Main Loop ---
EPOCHS = 50
PATIENCE = 8
best_val_macro_f1 = 0.0
epochs_no_improve = 0
best_path = "best_resnet50.pt"
train_log = []

print(f"Starting training for {EPOCHS} epochs...")
for epoch in range(EPOCHS):
    epoch_start = time.time()
    # --- TRAINING PHASE ---
    model.train()
    running_loss = 0.0

    for batch in train_loader:
        inputs, labels = batch["pixel_values"].to(device), batch["label"].to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    # --- EVALUATION PHASE ---
    # 1. Evaluate on Training Data (Snapshot of current knowledge)
    train_acc, train_bal_acc, train_macro_f1 = evaluate_model(train_loader, model)

    # 2. Evaluate on Validation Data (Test on unseen data)
    val_acc, val_bal_acc, val_macro_f1 = evaluate_model(val_loader, model)

    # 3. Evaluate on Test Data (Test on seen data)
    test_acc, test_bal_acc, test_macro_f1 = evaluate_model(test_loader, model)

    epoch_time = time.time() - epoch_start
    train_log.append({
        "epoch": epoch + 1,
        "train_macro_f1": float(train_macro_f1),
        "val_macro_f1": float(val_macro_f1),
        "test_macro_f1": float(test_macro_f1),
        "epoch_time_sec": float(epoch_time),
    })

    # Print the detailed epoch report side-by-side
    print(f"\nEpoch {epoch+1}/{EPOCHS} Summary | Loss: {running_loss/len(train_loader):.4f} | Time: {epoch_time:.1f}s")
    print(f"  [TRAIN] Acc: {train_acc:.4f} | Bal Acc: {train_bal_acc:.4f} | Macro F1: {train_macro_f1:.4f}")
    print(f"  [VALID] Acc: {val_acc:.4f} | Bal Acc: {val_bal_acc:.4f} | Macro F1: {val_macro_f1:.4f}")
    print(f"  [TEST]  Acc: {test_acc:.4f} | Bal Acc: {test_bal_acc:.4f} | Macro F1: {test_macro_f1:.4f}")

    # Save checkpoint based on VALIDATION Macro F1
    if val_macro_f1 > best_val_macro_f1:
        best_val_macro_f1 = val_macro_f1
        epochs_no_improve = 0
        torch.save(model.state_dict(), best_path)
        print("  🌟 Checkpoint: New best model saved (based on Validation Macro F1)!")
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= PATIENCE:
            print(f"  Early stopping at epoch {epoch+1}")
            break

train_time_sec = float(sum(item["epoch_time_sec"] for item in train_log))
train_time_min = train_time_sec / 60.0

# 5. INFERENCE SPEED
print("\nMeasuring inference speed...")
inference = measure_inference_speed(model, test_loader, device)
gpu_peak_mb = (torch.cuda.max_memory_allocated() / (1024 ** 2)) if device.type == "cuda" else None
print(f"Inference Time: {inference['ms_per_batch']:.4f} ms/batch | {inference['images_per_sec']:.4f} images/sec")
print(f"GPU Peak Memory: {gpu_peak_mb:.4f} MB" if gpu_peak_mb is not None else "GPU Peak Memory: N/A (CPU)")

# 5b. LEARNING CURVES
train_f1s = [item["train_macro_f1"] for item in train_log]
test_f1s = [item["test_macro_f1"] for item in train_log]
epochs = [item["epoch"] for item in train_log]
plt.figure(figsize=(8, 5))
plt.plot(epochs, train_f1s, marker='o', label='Train Macro F1')
plt.plot(epochs, test_f1s, marker='o', label='Test Macro F1')
plt.xlabel('Epoch')
plt.ylabel('Macro F1')
plt.title('Frozen CNN Learning Curves (Train vs Test)')
plt.legend()
plt.tight_layout()
learning_curve_path = os.path.join(output_dir, "learning_curves.png")
plt.savefig(learning_curve_path, dpi=200, bbox_inches='tight')
plt.show()

# 5. CONFUSION MATRIX
print("\nGenerating Confusion Matrix...")
model.load_state_dict(torch.load(best_path)) # Load best weights
model.eval()

test_preds, test_labels = [], []
with torch.no_grad():
    for batch in test_loader:
        inputs, labels = batch["pixel_values"].to(device), batch["label"].to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        test_preds.extend(preds.cpu().numpy())
        test_labels.extend(labels.cpu().numpy())

cm = confusion_matrix(test_labels, test_preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('End-to-End Test Confusion Matrix')
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.xticks(rotation=45, ha='right'); plt.tight_layout()
cm_path = os.path.join(output_dir, "confusion_matrix.png")
plt.savefig(cm_path, dpi=200, bbox_inches='tight')
plt.show()

report = {
    "metrics": {
        "best_val_macro_f1": float(best_val_macro_f1),
        "test_macro_f1": float(f1_score(test_labels, test_preds, average='macro')),
    },
    "training_time_sec": train_time_sec,
    "training_time_min": train_time_min,
    "inference": inference,
    "gpu_peak_mb": float(gpu_peak_mb) if gpu_peak_mb is not None else None,
    "artifacts": {
        "learning_curves": learning_curve_path,
        "confusion_matrix": cm_path,
    },
}
with open(os.path.join(output_dir, "cnn_frozen_report.json"), "w") as f:
    json.dump(report, f, indent=2)

